name: test & maybe release

on:
  push:
    branches:
      - ${{{ github.default_branch }}}
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  js-test-and-release:
    uses: pl-strflt/uci/.github/workflows/js-test-and-release.yml@${{{ source.tag | split("-") | [(.[0] | split(".") | .[0:2] | join(".")), (.[1:])] | flatten | join("-") }}}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      UCI_GITHUB_TOKEN: ${{ secrets.UCI_GITHUB_TOKEN }}
